name: nhu_project
description: "A new Flutter project."

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  shared_preferences: ^2.2.2
  dio: ^5.9.0
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/drinks/orange_juice.jpg
    - assets/drinks/avocado_smoothie.jpg
    - assets/drinks/avocado_smoothie.jpg
    - assets/drinks/carrot_juice.jpg
    - assets/drinks/nut_milk.jpg
    - assets/drinks/coconut_water.jpg
    - assets/drinks/green_tea.jpg
    - assets/drinks/lemon_honey.jpg
    - assets/drinks/ginger_tea.jpg
    - assets/drinks/chamomile_tea.jpg
